# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Landtree\Documents\GitHub\LAN_Scan\Server_Side\LAN_Scan.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
import subprocess

class Ui_LanScan(object):
    def setupUi(self, LanScan):
        LanScan.setObjectName("LanScan")
        LanScan.resize(600, 375)
        self.centralwidget = QtWidgets.QWidget(LanScan)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 497, 33))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Label_Locate = QtWidgets.QLabel(self.layoutWidget)
        self.Label_Locate.setObjectName("Label_Locate")
        self.horizontalLayout.addWidget(self.Label_Locate)
        self.IPAddr = QtWidgets.QLineEdit(self.layoutWidget)
        self.IPAddr.setObjectName("IPAddr")
        self.horizontalLayout.addWidget(self.IPAddr)
        self.Btn_Connect = QtWidgets.QPushButton(self.layoutWidget)
        self.Btn_Connect.setObjectName("Btn_Connect")
        self.horizontalLayout.addWidget(self.Btn_Connect)
        self.HostName = QtWidgets.QComboBox(self.layoutWidget)
        self.HostName.setObjectName("HostName")
        self.HostName.addItem("")
        self.HostName.addItem("")
        self.horizontalLayout.addWidget(self.HostName)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 90, 191, 81))
        self.groupBox.setObjectName("groupBox")
        self.imgPerAng = QtWidgets.QPlainTextEdit(self.groupBox)
        self.imgPerAng.setGeometry(QtCore.QRect(110, 20, 61, 21))
        self.imgPerAng.setObjectName("imgPerAng")
        self.txtImgAng = QtWidgets.QLabel(self.groupBox)
        self.txtImgAng.setGeometry(QtCore.QRect(10, 20, 81, 16))
        self.txtImgAng.setObjectName("txtImgAng")
        self.numAngle = QtWidgets.QPlainTextEdit(self.groupBox)
        self.numAngle.setGeometry(QtCore.QRect(110, 50, 61, 21))
        self.numAngle.setObjectName("numAngle")
        self.txtNumAng = QtWidgets.QLabel(self.groupBox)
        self.txtNumAng.setGeometry(QtCore.QRect(10, 50, 81, 16))
        self.txtNumAng.setObjectName("txtNumAng")
        self.startScan = QtWidgets.QPushButton(self.centralwidget)
        self.startScan.setGeometry(QtCore.QRect(30, 220, 175, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.startScan.setFont(font)
        self.startScan.setObjectName("startScan")
        self.preView_btn = QtWidgets.QPushButton(self.centralwidget)
        self.preView_btn.setGeometry(QtCore.QRect(330, 260, 56, 17))
        self.preView_btn.setObjectName("preView_btn")
        self.imgPreview = QtWidgets.QGraphicsView(self.centralwidget)
        self.imgPreview.setGeometry(QtCore.QRect(240, 80, 231, 171))
        self.imgPreview.setObjectName("imgPreview")
        LanScan.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(LanScan)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 519, 18))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        LanScan.setMenuBar(self.menubar)
        self.pref = QtWidgets.QAction(LanScan)
        self.pref.setObjectName("pref")
        self.actionExit = QtWidgets.QAction(LanScan)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionExit)
        self.menuSettings.addAction(self.pref)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(LanScan)
        QtCore.QMetaObject.connectSlotsByName(LanScan)

    def retranslateUi(self, LanScan):
        _translate = QtCore.QCoreApplication.translate
        LanScan.setWindowTitle(_translate("LanScan", "LanScan"))
        self.Label_Locate.setText(_translate("LanScan", "Locate Scanner:"))
        self.IPAddr.setText(_translate("LanScan", "192.168.50.4"))
        self.Btn_Connect.setText(_translate("LanScan", "Connect"))
        self.HostName.setItemText(0, _translate("LanScan", "TTScan"))
        self.HostName.setItemText(1, _translate("LanScan", "192.168.50.4"))
        self.groupBox.setTitle(_translate("LanScan", "Scan Settings"))
        self.txtImgAng.setText(_translate("LanScan", "# of Images per angle"))
        self.txtNumAng.setText(_translate("LanScan", "# of angles (min 3)"))
        self.startScan.setText(_translate("LanScan", "Start Scan"))
        self.preView_btn.setText(_translate("LanScan", "preview"))
        self.menuFile.setTitle(_translate("LanScan", "File"))
        self.menuSettings.setTitle(_translate("LanScan", "Settings"))
        self.pref.setText(_translate("LanScan", "Preferences"))
        self.actionExit.setText(_translate("LanScan", "Exit"))

    def exit_click(self):
        exit()

def isScanAlive():
    ipAddr = ui.IPAddr.text()

    command = ['ping', ipAddr]  # '-c 4' sends 4 ICMP Echo Requests

    # Run the ping command
    process = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    stdout, stderr = process.communicate()

    # Decode output to handle bytes to string conversion
    output = stdout.decode('utf-8')  # Assuming UTF-8 encoding

    # Check if the ping was successful based on the return code
    if process.returncode == 0:
        print(f"Ping to {ipAddr} successful:\n{output}")
    else:
        print(f"Ping to {ipAddr} failed:\n{stderr.decode('utf-8')}")

def openSettings():
    try:
        subprocess.run(['python', r'C:\Users\Landtree\Documents\GitHub\LAN_Scan\Server_Side\Scan_settingsQT.py'], check=True)
    except subprocess.CalledProcessError as e:
        print(f"Failed to open settings: {e}")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_LanScan()
    ui.setupUi(MainWindow)
    MainWindow.show()
    ui.actionExit.triggered.connect(ui.exit_click)
    ui.Btn_Connect.pressed.connect(isScanAlive)
    ui.menuSettings.triggered.connect(openSettings)
    sys.exit(app.exec_())
